<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Regression – Quantifying the Impact of Day of Week</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="includes/styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Data Science for Marketers and Analysts</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Overview Concepts
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="what-is-data-science.html">What is Data Science?</a>
    </li>
    <li>
      <a href="what-is-machine-learning.html">What is Machine Learning?</a>
    </li>
    <li>
      <a href="what-is-ai.html">What is Artificial Intelligence?</a>
    </li>
    <li>
      <a href="myths-about-ai.html">Myths about AI</a>
    </li>
    <li>
      <a href="why-is-data-science-hard.html">Why Is Data Science So Hard (for Marketers)?</a>
    </li>
    <li>
      <a href="data-science-terminology.html">Data Science Terminlogy</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Statistical Methods
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="anova.html">ANOVA</a>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Regression</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="linear-vs-logistic.html">Linear vs. Logistic Regression</a>
        </li>
        <li>
          <a href="linear-regression-continuous.html">Linear Regression w/ Continuous Variables</a>
        </li>
        <li>
          <a href="linear-regression-nominal.html">Linear Regression w/ Nominal Variables</a>
        </li>
        <li>
          <a href="logistic-regression.html">Logistic Regression</a>
        </li>
      </ul>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://www.searchdiscovery.com">
    <span class="includes/logo includes/logo-sm.png"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->
<!-- Embed custom font -->
<link href="https://fonts.googleapis.com/css?family=Nunito&display=swap" rel="stylesheet" />

<!-- Favicon -->
<link rel="shortcut icon" href="includes/favicon.ico" />

<!-- Google Tag Manager container -->
<script>
(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WQR7N8');
</script>

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Regression – Quantifying the Impact of Day of Week</h1>

</div>


<p><img src="images/cartoon-fpo.png" /></p>
<ul>
<li>For additional examples, downloadable code, and explanations of the overall effort, see: <a href="https://github.com/SDITools/ga-and-r-examples" class="uri">https://github.com/SDITools/ga-and-r-examples</a></li>
<li>To see this specific example in Shiny (web/interactive) form, see: <a href="https://gilligan.shinyapps.io/regression/" class="uri">https://gilligan.shinyapps.io/regression/</a></li>
</ul>
<div id="overview" class="section level3">
<h3>Overview</h3>
<p>This example is an exploration of using linear regression with categorical/nominal variables. Specifically: with day of week. It will answer two questions:</p>
<ul>
<li><strong><em>What % of traffic (although it could be any metric) is explained simply by which day of the week it is?</em></strong></li>
<li><strong><em>What is the relative impact of each day of week on the overall traffic?</em></strong></li>
</ul>
<p>This is a bit of an odd way to go about this, in that we would typically perform “time-series decomposition” and then look at the details for a “7-day season.” In theory, that would return a pretty similar result. But, it’s instructive to walk through a regression to get an understanding on how to perform regression with categorical (aka, nominal) variables, which “day of week” actually is.</p>
<p><em>Note that this approach – unlike a time-series decomposition – does <strong>not</strong> take into account overall trends in the data, such as a general trend of increasing traffic over time. Again, though, that’s okay for shorter-term assessments, and for pedagogical purposes.</em></p>
<p>The broader application of this approach probably wouldn’t be on “traffic,” but, rather, would be on some form of conversion, and the model would give the multiplier for each session that had a given set of characteristics (e.g., a mobile visitor from paid search) on whatever that conversion (or other outcome – such as revenue) would have.</p>
<p>We’re only using “day of week” here because sessions is our independent variable, and a session is a session. So, a mobile visit from paid search contributes one session just like a tablet visit from organic search contributes one session – “characteristics of a session” don’t impact “the fact that it’s as session.” “What day of the week it is,” though, is an entirely independent variable, so it works to check the degree to which the day of week impacts the number of sessions.</p>
</div>
<div id="setupconfig" class="section level3">
<h3>Setup/Config</h3>
<p>Start by the initial configuration of variables.</p>
<pre class="r"><code># Load the necessary libraries. 
if (!require(&quot;pacman&quot;)) install.packages(&quot;pacman&quot;)</code></pre>
<pre><code>## Loading required package: pacman</code></pre>
<pre class="r"><code>pacman::p_load(googleAnalyticsR,  # How we actually get the Google Analytics data
               tidyverse,         # Includes dplyr, ggplot2, and others; very key!
               knitr,             # Nicer looking tables
               kableExtra,        # Even nicer looking tables
               plotly,            # We&#39;re going to make the charts interactive
               scales,            # Useful for some number formatting in the visualizations
               MASS)              # For our stepwise regression

# Authorize GA. Depending on if you&#39;ve done this already and a .ga-httr-oauth file has
# been saved or not, this may pop you over to a browser to authenticate.
ga_auth(token = &quot;.httr-oauth&quot;)

# Set the view ID and the date range. If you want to, you can swap out the Sys.getenv()
# call and just replace that with a hardcoded value for the view ID. 
view_id &lt;- Sys.getenv(&quot;GA_VIEW_ID&quot;)
start_date &lt;- Sys.Date() - 90        # The last 90 days
end_date &lt;- Sys.Date() - 1           # Yesterday

start_date &lt;- as.Date(&quot;2018-10-19&quot;)      # The last 90 days
end_date &lt;- as.Date(&quot;2019-01-16&quot;)           # Yesterday

# Define our theme -- this will be used later for visualizations
theme_main &lt;- theme_light() +
  theme(text = element_text(family=&quot;Nunito&quot;),
        plot.title = element_text(hjust=0.5, size=18, face=&quot;bold&quot;),
        legend.title = element_blank(),
        axis.text = element_text(size=16),
        axis.text.x = element_text(face = &quot;bold&quot;, margin = margin(t = 5, unit = &quot;pt&quot;)),
        axis.line.x = element_line(color = &quot;gray20&quot;, size=0.5),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        legend.position = &quot;top&quot;,
        panel.border = element_blank(),
        panel.grid.major.y = element_line(color = &quot;gray80&quot;),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())</code></pre>
</div>
<div id="pull-the-data" class="section level3">
<h3>Pull the Data</h3>
<p>This is a simple data pull. We’re just pulling data by day (because each day is a different day of the week) and sessions. And, since Google Analytics has a “Day of Week Name” dimension, we’ll go ahead and pull that, too (although we could have easily calculated this afterwards).</p>
<pre class="r"><code># Pull the data. See ?google_analytics_4() for additional parameters. The anti_sample = TRUE
# parameter will slow the query down a smidge and isn&#39;t strictly necessary, but it will
# ensure you do not get sampled data.
ga_data &lt;- google_analytics(viewId = view_id,
                            date_range = c(start_date, end_date),
                            metrics = &quot;sessions&quot;,
                            dimensions = c(&quot;date&quot;, &quot;dayOfWeekName&quot;),
                            anti_sample = TRUE)

# Shorten the day of week values and make it a factor with and order for easier plotting later
# Check the variability of data by weekday
ga_data &lt;- ga_data %&gt;% 
  mutate(Weekday = substring(dayOfWeekName, 1, 3)) %&gt;% 
  mutate(Weekday = toupper(Weekday)) %&gt;% 
  mutate(Weekday = factor(Weekday,
                          levels = c(&quot;SUN&quot;, &quot;MON&quot;, &quot;TUE&quot;, &quot;WED&quot;, &quot;THU&quot;, &quot;FRI&quot;, &quot;SAT&quot;))) %&gt;% 
  dplyr::select(date, Weekday, sessions)

names(ga_data) &lt;- c(&quot;Date&quot;, &quot;Weekday&quot;, &quot;Sessions&quot;)

# Show the head of the returned data
head(ga_data, 12) %&gt;% kable() %&gt;% kable_styling(full_width = F,
                                                font_size = 24,
                                                bootstrap_options = &quot;condensed&quot;) %&gt;% 
  column_spec(1, width = &quot;8em&quot;) %&gt;% 
  column_spec(2, width = &quot;6em&quot;) %&gt;% 
  column_spec(3, width = &quot;6em&quot;)</code></pre>
<table class="table table-condensed" style="font-size: 24px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Date
</th>
<th style="text-align:left;">
Weekday
</th>
<th style="text-align:right;">
Sessions
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;width: 8em; ">
2018-10-19
</td>
<td style="text-align:left;width: 6em; ">
FRI
</td>
<td style="text-align:right;width: 6em; ">
6564
</td>
</tr>
<tr>
<td style="text-align:left;width: 8em; ">
2018-10-20
</td>
<td style="text-align:left;width: 6em; ">
SAT
</td>
<td style="text-align:right;width: 6em; ">
4574
</td>
</tr>
<tr>
<td style="text-align:left;width: 8em; ">
2018-10-21
</td>
<td style="text-align:left;width: 6em; ">
SUN
</td>
<td style="text-align:right;width: 6em; ">
4133
</td>
</tr>
<tr>
<td style="text-align:left;width: 8em; ">
2018-10-22
</td>
<td style="text-align:left;width: 6em; ">
MON
</td>
<td style="text-align:right;width: 6em; ">
7237
</td>
</tr>
<tr>
<td style="text-align:left;width: 8em; ">
2018-10-23
</td>
<td style="text-align:left;width: 6em; ">
TUE
</td>
<td style="text-align:right;width: 6em; ">
6786
</td>
</tr>
<tr>
<td style="text-align:left;width: 8em; ">
2018-10-24
</td>
<td style="text-align:left;width: 6em; ">
WED
</td>
<td style="text-align:right;width: 6em; ">
6660
</td>
</tr>
<tr>
<td style="text-align:left;width: 8em; ">
2018-10-25
</td>
<td style="text-align:left;width: 6em; ">
THU
</td>
<td style="text-align:right;width: 6em; ">
6957
</td>
</tr>
<tr>
<td style="text-align:left;width: 8em; ">
2018-10-26
</td>
<td style="text-align:left;width: 6em; ">
FRI
</td>
<td style="text-align:right;width: 6em; ">
6580
</td>
</tr>
<tr>
<td style="text-align:left;width: 8em; ">
2018-10-27
</td>
<td style="text-align:left;width: 6em; ">
SAT
</td>
<td style="text-align:right;width: 6em; ">
4735
</td>
</tr>
<tr>
<td style="text-align:left;width: 8em; ">
2018-10-28
</td>
<td style="text-align:left;width: 6em; ">
SUN
</td>
<td style="text-align:right;width: 6em; ">
4370
</td>
</tr>
<tr>
<td style="text-align:left;width: 8em; ">
2018-10-29
</td>
<td style="text-align:left;width: 6em; ">
MON
</td>
<td style="text-align:right;width: 6em; ">
7725
</td>
</tr>
<tr>
<td style="text-align:left;width: 8em; ">
2018-10-30
</td>
<td style="text-align:left;width: 6em; ">
TUE
</td>
<td style="text-align:right;width: 6em; ">
7434
</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Go ahead and do a quick visualization of the resulting data
gg &lt;- ggplot(ga_data, aes(x = Date, y = Sessions)) + 
  geom_line(color = &quot;#9a258f&quot;, size=1) +
  scale_y_continuous(expand = c(0,0), limits=c(0, max(ga_data$Sessions)*1.05), label = comma) +
  labs(title = &quot;Sessions by Day&quot;,
       x = &quot;Date&quot;) +
  theme_main

gg</code></pre>
<p><img src="linear-regression-nominal_files/figure-html/base-data-viz-1.png" width="960" /></p>
<p>This step is not really necessary to do the regression. It’s just useful to realize that, essentially, we’re looking at all of the dates, organized by weekday, and the median and variability, as well as how many outliers there are, helps with some intuition for later.</p>
<pre class="r"><code># Make a boxplot where we combine all of the data points for each day of week together
gg &lt;- ggplot(ga_data, aes(x = Weekday, y = Sessions)) + 
  geom_boxplot(fill = &quot;gray90&quot;, color = &quot;gray40&quot;, outlier.colour = &quot;#9a258f&quot;, outlier.size=2.5) +
  scale_y_continuous(expand = c(0,0), limits=c(0, max(ga_data$Sessions)*1.05), label = comma) +
  labs(title = &quot;Sessions Variation by Day of Week&quot;) +
  theme_main
gg</code></pre>
<p><img src="linear-regression-nominal_files/figure-html/week-data-viz-1.png" width="960" /></p>
</div>
<div id="data-munging" class="section level3">
<h3>Data Munging</h3>
<p>We need convert each day of week to a binary – or “dummy” – variable. This will make sense as we get into it.</p>
<p>Note that the last step in this munging drops the “Saturday” column entirely. <em>Any</em> day of the week could be excluded. This gets explained by saying, “we only need <em>k-1</em> values,” but, to maybe provide a bit more intuition, this really is pointing out that, if there are 7 possible days of the week, then we only need 6 variables to identify each observation (each row of data) by day. In the way this example is set up, we don’t need Saturday, because we know that any row that is not Sunday, Monday, Tuesday, Wednesday, Thursday, or Friday <em>must</em> be Saturday.</p>
<p>It doesn’t really matter <em>which</em> variable you drop (you can update the code to drop a different day and see that, while the resulting model has different coefficients, it actually returns the exact same results).</p>
<pre class="r"><code># Get the data set up where each day of the week has its own column. That means one of the 
# columns will be a &quot;1&quot; and the rest will be &quot;0s&quot; for each date
ga_data_dummies &lt;- ga_data %&gt;% 
  mutate(var = 1) %&gt;%                                          # Put a 1 in all reows of a column
  spread(key = Weekday, value = var, fill = 0) %&gt;%             # Create the dummy variables
  dplyr::select(Date, SUN, MON, TUE, WED, THU, FRI, Sessions)  # Re-order and drop &quot;SAT&quot;

# Display what the data now looks like
kable(head(ga_data_dummies, 12)) %&gt;% kable_styling(full_width = F,
                                                font_size = 24,
                                                bootstrap_options = &quot;condensed&quot;) %&gt;%  
  column_spec(1, width = &quot;10em&quot;) %&gt;% 
  column_spec(2:7, width = &quot;5em&quot;) %&gt;% 
  column_spec(8, width = &quot;8em&quot;)</code></pre>
<table class="table table-condensed" style="font-size: 24px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Date
</th>
<th style="text-align:right;">
SUN
</th>
<th style="text-align:right;">
MON
</th>
<th style="text-align:right;">
TUE
</th>
<th style="text-align:right;">
WED
</th>
<th style="text-align:right;">
THU
</th>
<th style="text-align:right;">
FRI
</th>
<th style="text-align:right;">
Sessions
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;width: 10em; ">
2018-10-19
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
1
</td>
<td style="text-align:right;width: 8em; ">
6564
</td>
</tr>
<tr>
<td style="text-align:left;width: 10em; ">
2018-10-20
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 8em; ">
4574
</td>
</tr>
<tr>
<td style="text-align:left;width: 10em; ">
2018-10-21
</td>
<td style="text-align:right;width: 5em; ">
1
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 8em; ">
4133
</td>
</tr>
<tr>
<td style="text-align:left;width: 10em; ">
2018-10-22
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
1
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 8em; ">
7237
</td>
</tr>
<tr>
<td style="text-align:left;width: 10em; ">
2018-10-23
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
1
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 8em; ">
6786
</td>
</tr>
<tr>
<td style="text-align:left;width: 10em; ">
2018-10-24
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
1
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 8em; ">
6660
</td>
</tr>
<tr>
<td style="text-align:left;width: 10em; ">
2018-10-25
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
1
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 8em; ">
6957
</td>
</tr>
<tr>
<td style="text-align:left;width: 10em; ">
2018-10-26
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
1
</td>
<td style="text-align:right;width: 8em; ">
6580
</td>
</tr>
<tr>
<td style="text-align:left;width: 10em; ">
2018-10-27
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 8em; ">
4735
</td>
</tr>
<tr>
<td style="text-align:left;width: 10em; ">
2018-10-28
</td>
<td style="text-align:right;width: 5em; ">
1
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 8em; ">
4370
</td>
</tr>
<tr>
<td style="text-align:left;width: 10em; ">
2018-10-29
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
1
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 8em; ">
7725
</td>
</tr>
<tr>
<td style="text-align:left;width: 10em; ">
2018-10-30
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
1
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 8em; ">
7434
</td>
</tr>
</tbody>
</table>
<pre class="r"><code># When performing the regression, we don&#39;t actually need the date value, so make a data
# set that has that removed
analysis_data &lt;- ga_data_dummies %&gt;% dplyr::select(-Date)</code></pre>
</div>
<div id="conduct-a-stepwise-regression-on-all-data" class="section level3">
<h3>Conduct a Stepwise Regression on ALL Data</h3>
<p>This is the “easy” part. We’re just going to run a straight-up regression on all of the data. This has some problems, as there will be a tendency to overfit a model. We’ll come back to that in a bit!</p>
<p>This is a “stepwise regression,” in that it’s going to find the “best” subset of variables for fitting the model – dropping ones that are not really helping the cause. There are <em>tons</em> of articles and posts explaining the nuts and bolts of this, so Google away! Or, here’s one: <a href="http://www.sthda.com/english/articles/37-model-selection-essentials-in-r/154-stepwise-regression-essentials-in-r/" class="uri">http://www.sthda.com/english/articles/37-model-selection-essentials-in-r/154-stepwise-regression-essentials-in-r/</a>.</p>
<pre class="r"><code># Fit the full model 
full_model &lt;- lm(Sessions ~., data = analysis_data)

# Now, see if stepwise can knock some things out (it shouldn&#39;t in this case,
# but it doesn&#39;t hurt to try)
step_model &lt;- stepAIC(full_model, direction = &quot;both&quot;, trace = FALSE)</code></pre>
</div>
<div id="evaluate-the-model" class="section level3">
<h3>Evaluate the Model</h3>
<p>Let’s look a summary of the model:</p>
<pre class="r"><code># Get just the overall model summary
model_summary &lt;- summary(step_model)

# Output that summary
model_summary</code></pre>
<pre><code>## 
## Call:
## lm(formula = Sessions ~ SUN + MON + TUE + WED + THU + FRI, data = analysis_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4356.9  -319.7    79.0   380.3  2569.5 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   5090.2      268.2  18.979  &lt; 2e-16 ***
## SUN           -632.0      379.3  -1.666   0.0994 .  
## MON           2515.5      379.3   6.632 3.15e-09 ***
## TUE           2071.2      379.3   5.461 4.84e-07 ***
## WED           2471.3      379.3   6.515 5.27e-09 ***
## THU           2662.7      387.1   6.878 1.05e-09 ***
## FRI           2167.5      379.3   5.714 1.67e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 967 on 83 degrees of freedom
## Multiple R-squared:  0.6424, Adjusted R-squared:  0.6165 
## F-statistic: 24.85 on 6 and 83 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>This <em>can</em> be a bit confusing to read, so let’s try to come up with something that, perhaps, is a bit easier to read.</p>
<p>Start by getting the p-value and the adjusted R-squared for the model overall.</p>
<pre class="r"><code># Get the p-value and the adjusted R-Squared for the model overall

# Get the F-statistic
f_statistic &lt;- model_summary$fstatistic

# Get the p_value
p_value &lt;- pf(f_statistic[1], f_statistic[2], f_statistic[3],lower.tail=F)
attributes(p_value) &lt;- NULL

# Get the adjusted R-squared
adj_r_sq &lt;- model_summary$adj.r.squared</code></pre>
<p>This shows us that the model overall:</p>
<ul>
<li>Has a p-value of <strong>0.0000</strong></li>
<li>Has an adjusted R<sup>2</sup> of <strong>0.617</strong> (meaning 61.7% of the actual results are explained by the model).</li>
</ul>
<p>Now, let’s dig into the actual individual independent variables and their coefficients. This is just a lightly cleaned up visualization of the “variables list” from the model output above. Note that not all days may appear in this table, as the nature of the stepwise regression is that it will add and subtract different features (variables) trying to find the “best” model.</p>
<pre class="r"><code># Make a data frame with just the coefficients and their significance levels. This is converting
# the p-values to confidence levels
ind_vars &lt;- model_summary$coefficients %&gt;% as.data.frame() %&gt;% 
  mutate(Variable = rownames(.), 
         Estimate = round(Estimate),
         `Confidence Level` = ifelse(`Pr(&gt;|t|)` &lt; 0.01, &quot;99%&quot;, 
                                     ifelse(`Pr(&gt;|t|)` &lt; 0.05, &quot;95%&quot;,
                                            ifelse(`Pr(&gt;|t|)` &lt; 0.1, &quot;90%&quot;, 
                                                   ifelse(`Pr(&gt;|t|)` &lt; 0.2, &quot;80%&quot;,&quot;&lt;80%&quot;))))) %&gt;% 
  dplyr::select(Variable, Coefficient = Estimate, `Confidence Level`)

# Output a table with the independent variables
kable(ind_vars, align = c(&quot;l&quot;, &quot;r&quot;, &quot;c&quot;)) %&gt;% 
  kable_styling(full_width = F, bootstrap_options = &quot;condensed&quot;, font_size=24) %&gt;% 
  column_spec(1, width = &quot;6em&quot;) %&gt;% 
  column_spec(2, width = &quot;6em&quot;) %&gt;% 
  column_spec(3, width = &quot;10em&quot;)</code></pre>
<table class="table table-condensed" style="font-size: 24px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Variable
</th>
<th style="text-align:right;">
Coefficient
</th>
<th style="text-align:center;">
Confidence Level
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;width: 6em; ">
(Intercept)
</td>
<td style="text-align:right;width: 6em; ">
5090
</td>
<td style="text-align:center;width: 10em; ">
99%
</td>
</tr>
<tr>
<td style="text-align:left;width: 6em; ">
SUN
</td>
<td style="text-align:right;width: 6em; ">
-632
</td>
<td style="text-align:center;width: 10em; ">
90%
</td>
</tr>
<tr>
<td style="text-align:left;width: 6em; ">
MON
</td>
<td style="text-align:right;width: 6em; ">
2515
</td>
<td style="text-align:center;width: 10em; ">
99%
</td>
</tr>
<tr>
<td style="text-align:left;width: 6em; ">
TUE
</td>
<td style="text-align:right;width: 6em; ">
2071
</td>
<td style="text-align:center;width: 10em; ">
99%
</td>
</tr>
<tr>
<td style="text-align:left;width: 6em; ">
WED
</td>
<td style="text-align:right;width: 6em; ">
2471
</td>
<td style="text-align:center;width: 10em; ">
99%
</td>
</tr>
<tr>
<td style="text-align:left;width: 6em; ">
THU
</td>
<td style="text-align:right;width: 6em; ">
2663
</td>
<td style="text-align:center;width: 10em; ">
99%
</td>
</tr>
<tr>
<td style="text-align:left;width: 6em; ">
FRI
</td>
<td style="text-align:right;width: 6em; ">
2168
</td>
<td style="text-align:center;width: 10em; ">
99%
</td>
</tr>
</tbody>
</table>
<p>It might be helpful to display the above in equation notation – just to get it mapped back to our days with algebra.</p>
<pre class="r"><code># Generate a string that introduces RMarkdown equation notation so that we have values that
# can be pasted together and output as RMarkdown. This gets a little screwy, but it&#39;s
# just so we can output a &quot;normal&quot; looking equation.
model_equation &lt;- ind_vars %&gt;% 
  mutate(rmd = ifelse(Variable == &quot;(Intercept)&quot;, round(Coefficient, 0),
                      paste0(round(Coefficient, 0), &quot; \\times &quot;, Variable))) 

model_equation &lt;- model_equation$rmd %&gt;%
  paste(collapse = &quot; + &quot;) %&gt;% 
  paste0(&quot;$$Sessions = &quot;, ., &quot;$$&quot;)</code></pre>
<p><strong><span class="math display">\[Sessions = 5090 + -632 \times SUN + 2515 \times MON + 2071 \times TUE + 2471 \times WED + 2663 \times THU + 2168 \times FRI\]</span></strong></p>
<p>But, wait. How do I multiply a number by a <em>day</em>?! This gets back to our creation of “dummy variables” earlier. Remember that the data we’re working with created a variable for each day of the week and then assigned each row in the table (each day, each “observation”) as a <code>1</code> (yes, it’s that day) or a <code>0</code> (no, it’s not that day). That means, in the equation above, <em>most</em> of the values will be multipled by <code>0</code> for any given day, while one value will be multiplied by <code>1</code>.</p>
<pre class="r"><code># Re-display what the data looks like with dummy variables
kable(head(ga_data_dummies, 12)) %&gt;% kable_styling(full_width = F,
                                                font_size = 24,
                                                bootstrap_options = &quot;condensed&quot;) %&gt;% 
  column_spec(1, width = &quot;10em&quot;) %&gt;% 
  column_spec(2:7, width = &quot;5em&quot;) %&gt;% 
  column_spec(8, width = &quot;8em&quot;)</code></pre>
<table class="table table-condensed" style="font-size: 24px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Date
</th>
<th style="text-align:right;">
SUN
</th>
<th style="text-align:right;">
MON
</th>
<th style="text-align:right;">
TUE
</th>
<th style="text-align:right;">
WED
</th>
<th style="text-align:right;">
THU
</th>
<th style="text-align:right;">
FRI
</th>
<th style="text-align:right;">
Sessions
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;width: 10em; ">
2018-10-19
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
1
</td>
<td style="text-align:right;width: 8em; ">
6564
</td>
</tr>
<tr>
<td style="text-align:left;width: 10em; ">
2018-10-20
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 8em; ">
4574
</td>
</tr>
<tr>
<td style="text-align:left;width: 10em; ">
2018-10-21
</td>
<td style="text-align:right;width: 5em; ">
1
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 8em; ">
4133
</td>
</tr>
<tr>
<td style="text-align:left;width: 10em; ">
2018-10-22
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
1
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 8em; ">
7237
</td>
</tr>
<tr>
<td style="text-align:left;width: 10em; ">
2018-10-23
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
1
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 8em; ">
6786
</td>
</tr>
<tr>
<td style="text-align:left;width: 10em; ">
2018-10-24
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
1
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 8em; ">
6660
</td>
</tr>
<tr>
<td style="text-align:left;width: 10em; ">
2018-10-25
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
1
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 8em; ">
6957
</td>
</tr>
<tr>
<td style="text-align:left;width: 10em; ">
2018-10-26
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
1
</td>
<td style="text-align:right;width: 8em; ">
6580
</td>
</tr>
<tr>
<td style="text-align:left;width: 10em; ">
2018-10-27
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 8em; ">
4735
</td>
</tr>
<tr>
<td style="text-align:left;width: 10em; ">
2018-10-28
</td>
<td style="text-align:right;width: 5em; ">
1
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 8em; ">
4370
</td>
</tr>
<tr>
<td style="text-align:left;width: 10em; ">
2018-10-29
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
1
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 8em; ">
7725
</td>
</tr>
<tr>
<td style="text-align:left;width: 10em; ">
2018-10-30
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
1
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 5em; ">
0
</td>
<td style="text-align:right;width: 8em; ">
7434
</td>
</tr>
</tbody>
</table>
</div>
<div id="compare-the-model-predictions-to-the-actuals" class="section level3">
<h3>Compare the Model Predictions to the Actuals</h3>
<p>So, what does our model <em>look like</em> when comparing its predictions to the actual data?</p>
<p>We can simply run the model on the original data set and return a plot that shows the actual vs. predicted values. This is a shortcut to “plotting the residuals” and other checks, but, hopefully, won’t give anyone using this too much heartburn.</p>
<p>Here’s your chance to check the math from the equation above with some of the actual data in the new data frame we’ve created.</p>
<pre class="r"><code># Predict the results using the data -- to get a visualization of the results (basically, 
# visualizing the residuals). This is just a vector of  predicted sessions.
predict_vs_actual &lt;- predict(step_model, ga_data_dummies)

# Add those predictions to a data frame that shows the actuals. We&#39;ll hold onto
# this so we can preview it in the output. 
predict_vs_actual_df &lt;- ga_data_dummies %&gt;% 
  cbind(data.frame(`Predicted Sessions` = predict_vs_actual)) %&gt;% 
  mutate(`Predicted.Sessions` = round(`Predicted.Sessions`))

# Rename &quot;Sessions&quot; to &quot;Actual Sessions&quot; for clarity
names(predict_vs_actual_df) &lt;- gsub(&quot;Sessions&quot;, &quot;Actual Sessions&quot;, names(predict_vs_actual_df)) %&gt;% 
  gsub(&quot;Predicted.Actual.Sessions&quot;, &quot;Predicted&quot;, .)

# Output the head
kable(head(predict_vs_actual_df, 12)) %&gt;% 
  kable_styling(full_width = F, bootstrap_options = &quot;condensed&quot;, font_size=20) %&gt;% 
  column_spec(1, width = &quot;60em&quot;) %&gt;% 
  column_spec(2:7, width = &quot;6em&quot;) %&gt;% 
  column_spec(8, width = &quot;80em&quot;) %&gt;% 
  column_spec(9, width = &quot;40em&quot;)</code></pre>
<table class="table table-condensed" style="font-size: 20px; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Date
</th>
<th style="text-align:right;">
SUN
</th>
<th style="text-align:right;">
MON
</th>
<th style="text-align:right;">
TUE
</th>
<th style="text-align:right;">
WED
</th>
<th style="text-align:right;">
THU
</th>
<th style="text-align:right;">
FRI
</th>
<th style="text-align:right;">
Actual Sessions
</th>
<th style="text-align:right;">
Predicted
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;width: 60em; ">
2018-10-19
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
1
</td>
<td style="text-align:right;width: 80em; ">
6564
</td>
<td style="text-align:right;width: 40em; ">
7258
</td>
</tr>
<tr>
<td style="text-align:left;width: 60em; ">
2018-10-20
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 80em; ">
4574
</td>
<td style="text-align:right;width: 40em; ">
5090
</td>
</tr>
<tr>
<td style="text-align:left;width: 60em; ">
2018-10-21
</td>
<td style="text-align:right;width: 6em; ">
1
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 80em; ">
4133
</td>
<td style="text-align:right;width: 40em; ">
4458
</td>
</tr>
<tr>
<td style="text-align:left;width: 60em; ">
2018-10-22
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
1
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 80em; ">
7237
</td>
<td style="text-align:right;width: 40em; ">
7606
</td>
</tr>
<tr>
<td style="text-align:left;width: 60em; ">
2018-10-23
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
1
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 80em; ">
6786
</td>
<td style="text-align:right;width: 40em; ">
7161
</td>
</tr>
<tr>
<td style="text-align:left;width: 60em; ">
2018-10-24
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
1
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 80em; ">
6660
</td>
<td style="text-align:right;width: 40em; ">
7562
</td>
</tr>
<tr>
<td style="text-align:left;width: 60em; ">
2018-10-25
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
1
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 80em; ">
6957
</td>
<td style="text-align:right;width: 40em; ">
7753
</td>
</tr>
<tr>
<td style="text-align:left;width: 60em; ">
2018-10-26
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
1
</td>
<td style="text-align:right;width: 80em; ">
6580
</td>
<td style="text-align:right;width: 40em; ">
7258
</td>
</tr>
<tr>
<td style="text-align:left;width: 60em; ">
2018-10-27
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 80em; ">
4735
</td>
<td style="text-align:right;width: 40em; ">
5090
</td>
</tr>
<tr>
<td style="text-align:left;width: 60em; ">
2018-10-28
</td>
<td style="text-align:right;width: 6em; ">
1
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 80em; ">
4370
</td>
<td style="text-align:right;width: 40em; ">
4458
</td>
</tr>
<tr>
<td style="text-align:left;width: 60em; ">
2018-10-29
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
1
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 80em; ">
7725
</td>
<td style="text-align:right;width: 40em; ">
7606
</td>
</tr>
<tr>
<td style="text-align:left;width: 60em; ">
2018-10-30
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
1
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 6em; ">
0
</td>
<td style="text-align:right;width: 80em; ">
7434
</td>
<td style="text-align:right;width: 40em; ">
7161
</td>
</tr>
</tbody>
</table>
<p>For reference (if you want to do some math with the above):</p>
<p><strong><span class="math display">\[Sessions = 5090 + -632 \times SUN + 2515 \times MON + 2071 \times TUE + 2471 \times WED + 2663 \times THU + 2168 \times FRI\]</span></strong></p>
</div>
<div id="plot-the-results" class="section level3">
<h3>Plot the Results</h3>
<p>Finally, let’s plot the results showing three things:</p>
<ul>
<li><strong>The Actual Sessions</strong></li>
<li><strong>The Predicted Sessions</strong> – what our regression model (which we determined explains 0.0062% of the actual results)</li>
<li><strong>The Intercept</strong> – this is the constant; think of it as the baseline from which each independent variable increases or decreases the prediction</li>
</ul>
<pre class="r"><code># Get just the intercept (for a horizontal line we&#39;ll add)
y_intercept &lt;- ind_vars %&gt;% filter(Variable == &quot;(Intercept)&quot;) %&gt;% 
  dplyr::select(Coefficient) %&gt;% as.numeric()

# Add that y-intercept as a constant to the data to be plotted. geom_hline()
# would be better for this, but I gave up fighting to get the legend I was
# wanting, so hacking around it this way
predict_vs_actual_for_plot &lt;- predict_vs_actual_df %&gt;% 
  mutate(Intercept = y_intercept)

# For cleaner plotting, convert that to a tidy format and then turn it into a ggplot
predict_vs_actual_for_plot &lt;- predict_vs_actual_for_plot %&gt;% 
  dplyr::select(Date = Date, `Actual Sessions`, `Predicted`, Intercept) %&gt;% 
  gather(key = metric, value = value, -Date) %&gt;% 
  # Total hack to add better spacing in the legend
  mutate(metric = paste0(metric, &quot;    &quot;))

# Get the max value so we can expand the limits
y_lim &lt;- max(predict_vs_actual_for_plot$value) * 1.1

# Plot the actuals vs. predicted. 
gg_predict_vs_actual &lt;- ggplot() +
  geom_line(data = predict_vs_actual_for_plot,
            mapping = aes(x = Date, y = value, color = metric, 
                          linetype = metric), size = 1) +
  # geom_hline(mapping = aes(linetype = &quot;Intercept&quot;, yintercept = y_intercept), 
  #            color=&quot;#ed1c24&quot;) +
  scale_color_manual(values=c(&quot;#9a258f&quot;, &quot;#ed1c24&quot;, &quot;gray30&quot; )) +
  scale_linetype_manual(values = c(&quot;solid&quot;, &quot;dashed&quot;, &quot;dotted&quot; )) +
  scale_y_continuous(expand = c(0,0), limits = c(0,y_lim), label=number_format(accuracy=1, big.mark=&quot;,&quot;)) +
  labs(x = &quot;Date&quot;, y = &quot;Sessions&quot;, title = &quot;Sessions by Day: Actual vs. Predicted&quot;) +
  # guides(fill=guide_legend(keywidth=0.8, keyheight=0.1, default.unit=&quot;inch&quot;)) +
  theme_main +
  theme(legend.key.width=unit(4,&quot;line&quot;),
        legend.text = element_text(size=16),
        axis.line.x = element_line(color = &quot;gray20&quot;),
        plot.title = element_blank())

# Output the chart
gg_predict_vs_actual </code></pre>
<p><img src="linear-regression-nominal_files/figure-html/plot_result-1.png" width="960" /></p>
<p>So, yes, the <strong>Predicted Sessions</strong> follow a recurring pattern. That’s because our categorical variable – day of week – only has seven values, so our model is destined to just repeat.</p>
<p>Of course, if there was another variable thrown in (that had significance), this may not be the case, as this recurring pattern would then have some other factor (or set of factors) layered on top of it that added more variability to the prediction.</p>
</div>
<div id="a-note-on-overfitting" class="section level3">
<h3>A Note on Overfitting</h3>
<p>In this example, we had a relatively small number of variables, and we used stepwise regression to pick the subset (which may be “all”) that were most predictive of the actual results.</p>
<p>We also did not look at interaction effects, because days of week are quite independent of each other.</p>
<p>Consider if, for instance, we had also used mobile device category and wanted to include the interactions between day of week <em>and</em> device category as a predictor of a result like orders or revenue, then we would have had a <em>bunch</em> more variables (either overtly or behind the scenes). In addition to each day of the week and each device category – the “main effects,” we would have a slew of “interaction effects” to consider as well: <code>Monday + Mobile</code>, <code>Monday + Tablet</code>, <code>Monday + Desktop</code>, <code>Tuesday + Mobile</code>, etc.</p>
<p>Conceivably, we would get to a point pretty easily where we had as many variables as we had observations, which causes all sorts of issues! But, even if things did not get that extreme, having many more variables to consider runs a greater risk of “overfitting the model.” One way to lessen the risk of this is to use <em>k</em>-fold cross validation, which is a mechanism by which the data set is iteratively split into “training” and “testing” groups, and then the different models are run on different sets of training data and then evaluated based on how well they then predict the results in the test data.</p>
<p>We started to include that in this simple model… but, given the (relative) simplicity of this example, we determined it was not sufficiently illustrative to warrant including.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
